version: 1.2.3-{build}

branches:
  only:
    - master
    - develop

notifications:
  - provider: Email
    to:
      - me@patrick.codes
    on_build_status_changed: true

environment:
  matrix:
  - nodejs_version: "0.8"
  - nodejs_version: "0.10"
  - nodejs_version: "0.12"
  - nodejs_version: "1"
  - nodejs_version: "4"
  - nodejs_version: "5"
  - nodejs_version: "8"
  - nodejs_version: "10"
  - nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

platform:
  - x86
  - x64

test_script:
  - node --version
  - npm --version
  - npm test

build: off

matrix:
  fast_finish: true
